[pytest]
log_cli = false
log_cli_level = INFO

markers =
    read_only_test_warehouse: Tests that only read from the test data warehouse.
    read_write_evaluation_template: Tests that require read and write access to an empty evaluation template.
    read_only_evaluation_template: Tests that only read from an empty evaluation template.