[pytest]
log_cli = false
log_cli_level = INFO

markers =
    session_scope_evaluation_template
    session_scope_test_warehouse
    module_scope_test_warehouse
    function_scope_evaluation_template
    function_scope_test_warehouse
    function_scope_large_ensemble_warehouse
    function_scope_small_ensemble_warehouse
    function_scope_two_location_warehouse
    spark_shared_session