apiVersion: v1
kind: PersistentVolume
metadata:
  name: teehr-hub-data-nfs
spec:
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  nfs:
    server: $NFS_SERVER_DNS
    path: "/teehr-hub"
  mountOptions:
        - rsize=1048576
        - wsize=1048576
        - timeo=600
        - soft # We pick soft over hard, so NFS lockups don't lead to hung processes
        - retrans=2
        - noresvport
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-nfs
spec:
  accessModes:
    - ReadWriteMany
  volumeName: teehr-hub-data-nfs
  storageClassName: ""
  resources:
    requests:
      storage: 1Mi
