version = "3.8.1"

runner.dialect = scala213

maxColumn = 100
indentOperator.excludeRegex = "^(&&|\\|\\||!=|==)"
spaces.inImportCurlyBraces = true
trailingCommas = preserve
rewrite.rules = [
  RedundantBraces,
  RedundantParens,
  SortModifiers
]

align.preset = more
align.multiline = true
