name: build-push-teehr-hub-release

on:
  workflow_call:
    inputs:
      image-tag:
        description: "The image tag to use for the Docker image"
        required: true
        type: string
    # workflows: ["build-publish-package"]  # Triggered by "build-publish-package" workflow
    # types: [completed]                    # Trigger when "build-publish-package" completes

jobs:
  get-existing-version:
    runs-on: ubuntu-latest
    outputs:
      pypi_version: ${{ steps.get_pypi_version.outputs.package_version }}
    steps:
      - name: Get Package Version from PyPI
        id: get_pypi_version
        run: |
          PACKAGE_VERSION=v$(curl -s https://pypi.org/pypi/teehr/json | jq -r '.info.version')
          echo "package_version=$PACKAGE_VERSION" >> $GITHUB_OUTPUT

  call-docker-build:
    uses: RTIInternational/teehr-hub/.github/workflows/build-and-push-image.yaml@update-deployment
    secrets: inherit
    needs: get-existing-version
    with:
      image-tag: ${{ inputs.image-tag }}
      previous-image-tag: ${{ needs.get-existing-version.outputs.pypi_version }}