name: documentation

on:
  push:
    branches: [112-add-documentation]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install sphinx pydata-sphinx-theme myst-nb sphinx-design sphinx-autoapi numpydoc ghp-import -e .

      - name: Sphinx build
        run: |
          mkdir docs/sphinx/test_data
          cp tests/data/test_study/timeseries/*.parquet docs/sphinx/test_data
          cd docs/sphinx
          make clean html

      - name: Run ghp-import
        run: |
          ghp-import -n -p -f docs/sphinx/_build/html
