name: documentation

on:
  push:
    branches: [master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install sphinx pydata-sphinx-theme myst-nb sphinx-design sphinx-autoapi numpydoc ghp-import

      - name: Sphinx build
        run: |
          cd docs/sphinx
          make clean html

    #   - name: Deploy to GitHub Pages
    #     uses: peaceiris/actions-gh-pages@v3
    #     if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    #     with:
    #       publish_branch: gh-pages
    #       github_token: ${{ secrets.GITHUB_TOKEN }}
    #       publish_dir: docs/sphinx/_build/
    #       force_orphan: true

      - name: Run ghp-import
        run: |
          ghp-import -n -p -f docs/sphinx/_build/html
