name: documentation

on:
  push:
    # tags: [ 'v*.*.*' ]
    branches: [189-api-docs-are-broken]

permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install sphinx pydata-sphinx-theme myst-nb sphinx-design sphinx-autoapi numpydoc ghp-import -e .

      - name: Sphinx build
        run: |
          cd docs/sphinx
          make clean html

      - name: Run ghp-import
        run: |
          ghp-import -n -p -f docs/sphinx/_build/html
