name: documentation

on:
  push:
    # tags: [ 'v*.*.*' ]
    branches: [368-fix-user-guide-docs]

permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: test java
        run: |
          java --version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry config virtualenvs.create false
          poetry install
          python -m teehr.utils.install_spark_jars

      - name: Sphinx build
        run: |
          cd docs/sphinx
          make clean html

      - name: Run ghp-import
        run: |
          poetry add ghp-import
          ghp-import -n -p -f -o docs/sphinx/_build/html
