name: documentation

on:
  push:
    # tags: [ 'v*.*.*' ]
    branches: [368-fix-user-guide-docs]

permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry config virtualenvs.create false
          poetry install
          poetry add ghp-import
          python -m teehr.utils.install_spark_jars

      - name: Set pyspark environment variables
        run: |
          import os
          import sys

          os.environ['PYSPARK_PYTHON'] = sys.executable
          os.environ['PYSPARK_DRIVER_PYTHON'] = sys.executable
        shell: python

      - name: Sphinx build
        run: |
          cd docs/sphinx
          make clean html

      - name: Run ghp-import
        run: |
          ghp-import -n -p -f -o docs/sphinx/_build/html
