name: documentation

on:
  push:
    # tags: [ 'v*.*.*' ]
    branches: [346-fix-user-guide-notebooks]

permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install sphinx==7.2.6 pydata-sphinx-theme==0.15.4 myst-nb==1.1.2 sphinx-design numpy==1.26.4 numpydoc ghp-import pickleshare -e .

      - name: Sphinx build
        run: |
          cd docs/sphinx
          make clean html

      - name: Run ghp-import
        run: |
          ghp-import -n -p -f -o docs/sphinx/_build/html
