name: build-publish-documentation

on:
  workflow_dispatch:

  # pull_request:
  #   types: [opened, reopened, ready_for_review]
  #   branches: [main]

  push:
    branches: [main]


permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          export PATH="$HOME/.local/bin:$PATH"

      - name: Install dependencies
        run: |
          poetry config virtualenvs.create false
          poetry install --with dev

      - name: Sphinx build
        run: |
          cd docs/sphinx
          make clean html

      - name: Run ghp-import
        run: |
          poetry add ghp-import
          ghp-import -n -p -f -o docs/sphinx/_build/html
